---
stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - command test
  only:
    - master

build:
  stage: build
  script:
    - command build
  only:
    - master

deploy:
  stage: deploy
  script:
    - command deploy
  only:
    - master

...
