[package]
name = "cas-client"
version = "0.2.0"
authors = ["JMarignale <julien.marignale@gmail.com>"]
edition = "2018"

[lib]
name = "cas_client"
path = "src/lib.rs"

[workspace]
members = [
    ".",
    "cas-client-actix",
    "cas-client-core",
    "examples/actix-web-example",
]

[features]
default = []
actix-framework = [ "cas-client-actix" ]

[dependencies]
# COMMONS
cas-client-core = { path = "./cas-client-core" }

# ACTIX-FRAMEWORK feature
cas-client-actix = { path = "./cas-client-actix", optional = true }

[dev-dependencies]
actix-web = "1.0.3"
actix-files ="0.1.3"
actix-service = "0.4.1"
actix-session = "0.1.1"
dotenv = "0.14.1"
env_logger = "0.6.1"

[[example]]
name = "actix-web-example"
path = "examples/actix-web-example/src/main.rs"
required-features = ["actix-framework"]

[package.metadata.docs.rs]
all-features = true
