[package]
name = "cas_client"
version = "0.1.0"
authors = ["jmarignale"]
edition = "2018"

[features]
default = []
actix-framework = [ "actix-web", "actix-service", "actix-session", "futures" ]
actix-example = [ "dotenv" ]

[dependencies]
url = "= 1.7.2"
reqwest = "= 0.9.16"
roxmltree = "= 0.6.0"
serde = { version = "= 1.0.91", features = ["derive"] }
serde_json = "= 1.0.39"
log = "= 0.4.6"
env_logger = "= 0.6.1"

# ACTIX
actix-web = { version = "= 1.0.2", optional = true }
actix-service = { version = "= 0.4.1", optional = true }
actix-session = { version = "= 0.1.1", optional = true }
futures = { version = "= 0.1.27", optional = true }
dotenv = { version = "= 0.14.1", optional = true }

[[example]]
name = "actix_example"
required-features = ["actix-framework"]

[lib]
name = "cas_client"
path = "src/lib.rs"
